package Gpcs.oracle.apps.ak.gpcs.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GPCSLoginVORowImpl extends OAViewRowImpl {
    public static final int INVENTORYID = 0;
    public static final int ITEMNUMBER = 1;
    public static final int DESCRIPTION = 2;
    public static final int LONGDESCRIPTION = 3;
    public static final int MARKETDESCRIPTION = 4;
    public static final int TEMPLATENAME = 5;
    public static final int ITEMTYPE = 6;
    public static final int PRODUCTLINE = 7;
    public static final int MARKETINGMODEL = 8;
    public static final int PRIMARYUOMCODE = 9;
    public static final int BIGCLASS = 10;
    public static final int MIDDLECLASS = 11;
    public static final int COLOR = 12;
    public static final int BRANDNAME = 13;
    public static final int COUNTRYOFORIGIN = 14;
    public static final int EANCODE = 15;
    public static final int REGULATORYNAME = 16;
    public static final int UPCCODE = 17;
    public static final int JANCODE = 18;
    public static final int MINQUANTITY = 19;
    public static final int MAXQUANTITY = 20;
    public static final int LASTUPDATEDATE = 21;
    public static final int PRODUCTSEGMENT = 22;
    public static final int FGBIGCLASS = 23;
    public static final int USWARRANTY = 24;
    public static final int USUNITTIME = 25;
    public static final int CAWARRANTY = 26;
    public static final int CAUNITTIME = 27;

    /**This is the default constructor (do not remove)
     */
    public GPCSLoginVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute Inventoryid
     */
    public Number getInventoryid() {
        return (Number) getAttributeInternal(INVENTORYID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Inventoryid
     */
    public void setInventoryid(Number value) {
        setAttributeInternal(INVENTORYID, value);
    }

    /**Gets the attribute value for the calculated attribute Itemnumber
     */
    public String getItemnumber() {
        return (String) getAttributeInternal(ITEMNUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Itemnumber
     */
    public void setItemnumber(String value) {
        setAttributeInternal(ITEMNUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute Description
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**Gets the attribute value for the calculated attribute Longdescription
     */
    public String getLongdescription() {
        return (String) getAttributeInternal(LONGDESCRIPTION);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Longdescription
     */
    public void setLongdescription(String value) {
        setAttributeInternal(LONGDESCRIPTION, value);
    }

    /**Gets the attribute value for the calculated attribute Marketdescription
     */
    public String getMarketdescription() {
        return (String) getAttributeInternal(MARKETDESCRIPTION);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Marketdescription
     */
    public void setMarketdescription(String value) {
        setAttributeInternal(MARKETDESCRIPTION, value);
    }

    /**Gets the attribute value for the calculated attribute Templatename
     */
    public String getTemplatename() {
        return (String) getAttributeInternal(TEMPLATENAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Templatename
     */
    public void setTemplatename(String value) {
        setAttributeInternal(TEMPLATENAME, value);
    }

    /**Gets the attribute value for the calculated attribute Itemtype
     */
    public String getItemtype() {
        return (String) getAttributeInternal(ITEMTYPE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Itemtype
     */
    public void setItemtype(String value) {
        setAttributeInternal(ITEMTYPE, value);
    }

    /**Gets the attribute value for the calculated attribute Productline
     */
    public String getProductline() {
        return (String) getAttributeInternal(PRODUCTLINE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Productline
     */
    public void setProductline(String value) {
        setAttributeInternal(PRODUCTLINE, value);
    }

    /**Gets the attribute value for the calculated attribute Marketingmodel
     */
    public String getMarketingmodel() {
        return (String) getAttributeInternal(MARKETINGMODEL);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Marketingmodel
     */
    public void setMarketingmodel(String value) {
        setAttributeInternal(MARKETINGMODEL, value);
    }

    /**Gets the attribute value for the calculated attribute Primaryuomcode
     */
    public String getPrimaryuomcode() {
        return (String) getAttributeInternal(PRIMARYUOMCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Primaryuomcode
     */
    public void setPrimaryuomcode(String value) {
        setAttributeInternal(PRIMARYUOMCODE, value);
    }

    /**Gets the attribute value for the calculated attribute Bigclass
     */
    public String getBigclass() {
        return (String) getAttributeInternal(BIGCLASS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Bigclass
     */
    public void setBigclass(String value) {
        setAttributeInternal(BIGCLASS, value);
    }

    /**Gets the attribute value for the calculated attribute Middleclass
     */
    public String getMiddleclass() {
        return (String) getAttributeInternal(MIDDLECLASS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Middleclass
     */
    public void setMiddleclass(String value) {
        setAttributeInternal(MIDDLECLASS, value);
    }

    /**Gets the attribute value for the calculated attribute Color
     */
    public String getColor() {
        return (String) getAttributeInternal(COLOR);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Color
     */
    public void setColor(String value) {
        setAttributeInternal(COLOR, value);
    }

    /**Gets the attribute value for the calculated attribute Brandname
     */
    public String getBrandname() {
        return (String) getAttributeInternal(BRANDNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Brandname
     */
    public void setBrandname(String value) {
        setAttributeInternal(BRANDNAME, value);
    }

    /**Gets the attribute value for the calculated attribute Countryoforigin
     */
    public String getCountryoforigin() {
        return (String) getAttributeInternal(COUNTRYOFORIGIN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Countryoforigin
     */
    public void setCountryoforigin(String value) {
        setAttributeInternal(COUNTRYOFORIGIN, value);
    }

    /**Gets the attribute value for the calculated attribute Eancode
     */
    public String getEancode() {
        return (String) getAttributeInternal(EANCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Eancode
     */
    public void setEancode(String value) {
        setAttributeInternal(EANCODE, value);
    }

    /**Gets the attribute value for the calculated attribute Regulatoryname
     */
    public String getRegulatoryname() {
        return (String) getAttributeInternal(REGULATORYNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Regulatoryname
     */
    public void setRegulatoryname(String value) {
        setAttributeInternal(REGULATORYNAME, value);
    }

    /**Gets the attribute value for the calculated attribute Upccode
     */
    public String getUpccode() {
        return (String) getAttributeInternal(UPCCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Upccode
     */
    public void setUpccode(String value) {
        setAttributeInternal(UPCCODE, value);
    }

    /**Gets the attribute value for the calculated attribute Jancode
     */
    public String getJancode() {
        return (String) getAttributeInternal(JANCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Jancode
     */
    public void setJancode(String value) {
        setAttributeInternal(JANCODE, value);
    }

    /**Gets the attribute value for the calculated attribute Minquantity
     */
    public Number getMinquantity() {
        return (Number) getAttributeInternal(MINQUANTITY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Minquantity
     */
    public void setMinquantity(Number value) {
        setAttributeInternal(MINQUANTITY, value);
    }

    /**Gets the attribute value for the calculated attribute Maxquantity
     */
    public Number getMaxquantity() {
        return (Number) getAttributeInternal(MAXQUANTITY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Maxquantity
     */
    public void setMaxquantity(Number value) {
        setAttributeInternal(MAXQUANTITY, value);
    }

    /**Gets the attribute value for the calculated attribute Lastupdatedate
     */
    public Date getLastupdatedate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Lastupdatedate
     */
    public void setLastupdatedate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for the calculated attribute Productsegment
     */
    public String getProductsegment() {
        return (String) getAttributeInternal(PRODUCTSEGMENT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Productsegment
     */
    public void setProductsegment(String value) {
        setAttributeInternal(PRODUCTSEGMENT, value);
    }

    /**Gets the attribute value for the calculated attribute Fgbigclass
     */
    public String getFgbigclass() {
        return (String) getAttributeInternal(FGBIGCLASS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Fgbigclass
     */
    public void setFgbigclass(String value) {
        setAttributeInternal(FGBIGCLASS, value);
    }

    /**Gets the attribute value for the calculated attribute Uswarranty
     */
    public Number getUswarranty() {
        return (Number) getAttributeInternal(USWARRANTY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Uswarranty
     */
    public void setUswarranty(Number value) {
        setAttributeInternal(USWARRANTY, value);
    }

    /**Gets the attribute value for the calculated attribute Usunittime
     */
    public String getUsunittime() {
        return (String) getAttributeInternal(USUNITTIME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Usunittime
     */
    public void setUsunittime(String value) {
        setAttributeInternal(USUNITTIME, value);
    }

    /**Gets the attribute value for the calculated attribute Cawarranty
     */
    public Number getCawarranty() {
        return (Number) getAttributeInternal(CAWARRANTY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Cawarranty
     */
    public void setCawarranty(Number value) {
        setAttributeInternal(CAWARRANTY, value);
    }

    /**Gets the attribute value for the calculated attribute Caunittime
     */
    public String getCaunittime() {
        return (String) getAttributeInternal(CAUNITTIME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Caunittime
     */
    public void setCaunittime(String value) {
        setAttributeInternal(CAUNITTIME, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case INVENTORYID:
            return getInventoryid();
        case ITEMNUMBER:
            return getItemnumber();
        case DESCRIPTION:
            return getDescription();
        case LONGDESCRIPTION:
            return getLongdescription();
        case MARKETDESCRIPTION:
            return getMarketdescription();
        case TEMPLATENAME:
            return getTemplatename();
        case ITEMTYPE:
            return getItemtype();
        case PRODUCTLINE:
            return getProductline();
        case MARKETINGMODEL:
            return getMarketingmodel();
        case PRIMARYUOMCODE:
            return getPrimaryuomcode();
        case BIGCLASS:
            return getBigclass();
        case MIDDLECLASS:
            return getMiddleclass();
        case COLOR:
            return getColor();
        case BRANDNAME:
            return getBrandname();
        case COUNTRYOFORIGIN:
            return getCountryoforigin();
        case EANCODE:
            return getEancode();
        case REGULATORYNAME:
            return getRegulatoryname();
        case UPCCODE:
            return getUpccode();
        case JANCODE:
            return getJancode();
        case MINQUANTITY:
            return getMinquantity();
        case MAXQUANTITY:
            return getMaxquantity();
        case LASTUPDATEDATE:
            return getLastupdatedate();
        case PRODUCTSEGMENT:
            return getProductsegment();
        case FGBIGCLASS:
            return getFgbigclass();
        case USWARRANTY:
            return getUswarranty();
        case USUNITTIME:
            return getUsunittime();
        case CAWARRANTY:
            return getCawarranty();
        case CAUNITTIME:
            return getCaunittime();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case INVENTORYID:
            setInventoryid((Number)value);
            return;
        case ITEMNUMBER:
            setItemnumber((String)value);
            return;
        case DESCRIPTION:
            setDescription((String)value);
            return;
        case LONGDESCRIPTION:
            setLongdescription((String)value);
            return;
        case MARKETDESCRIPTION:
            setMarketdescription((String)value);
            return;
        case TEMPLATENAME:
            setTemplatename((String)value);
            return;
        case ITEMTYPE:
            setItemtype((String)value);
            return;
        case PRODUCTLINE:
            setProductline((String)value);
            return;
        case MARKETINGMODEL:
            setMarketingmodel((String)value);
            return;
        case PRIMARYUOMCODE:
            setPrimaryuomcode((String)value);
            return;
        case BIGCLASS:
            setBigclass((String)value);
            return;
        case MIDDLECLASS:
            setMiddleclass((String)value);
            return;
        case COLOR:
            setColor((String)value);
            return;
        case BRANDNAME:
            setBrandname((String)value);
            return;
        case COUNTRYOFORIGIN:
            setCountryoforigin((String)value);
            return;
        case EANCODE:
            setEancode((String)value);
            return;
        case REGULATORYNAME:
            setRegulatoryname((String)value);
            return;
        case UPCCODE:
            setUpccode((String)value);
            return;
        case JANCODE:
            setJancode((String)value);
            return;
        case MINQUANTITY:
            setMinquantity((Number)value);
            return;
        case MAXQUANTITY:
            setMaxquantity((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastupdatedate((Date)value);
            return;
        case PRODUCTSEGMENT:
            setProductsegment((String)value);
            return;
        case FGBIGCLASS:
            setFgbigclass((String)value);
            return;
        case USWARRANTY:
            setUswarranty((Number)value);
            return;
        case USUNITTIME:
            setUsunittime((String)value);
            return;
        case CAWARRANTY:
            setCawarranty((Number)value);
            return;
        case CAUNITTIME:
            setCaunittime((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
