package Gpcs.oracle.apps.ak.gpcs.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GPCSVORowImpl extends OAViewRowImpl {
    public static final int ITEMNUMBER = 0;
    public static final int DESCRIPTION = 1;
    public static final int LONGDESCRIPTION = 2;
    public static final int MARKETDESCRIPTION = 3;
    public static final int ITEMTYPE = 4;
    public static final int PRIMARYUOMCODE = 5;
    public static final int PRODUCTLINE = 6;
    public static final int BIGCLASS = 7;
    public static final int MIDDLECLASS = 8;
    public static final int BIGMIDDLECLASS = 9;
    public static final int MARKETINGMODEL = 10;
    public static final int LOCALMODEL = 11;
    public static final int COLOR = 12;
    public static final int BRANDNAME = 13;
    public static final int EANCODE = 14;
    public static final int REGULATORYNAME = 15;
    public static final int UPCCODE = 16;
    public static final int PRODUCTSEGMENT = 17;
    public static final int FGBIGCLASS = 18;

    /**This is the default constructor (do not remove)
     */
    public GPCSVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute Itemnumber
     */
    public String getItemnumber() {
        return (String) getAttributeInternal(ITEMNUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Itemnumber
     */
    public void setItemnumber(String value) {
        setAttributeInternal(ITEMNUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute Description
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**Gets the attribute value for the calculated attribute Longdescription
     */
    public String getLongdescription() {
        return (String) getAttributeInternal(LONGDESCRIPTION);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Longdescription
     */
    public void setLongdescription(String value) {
        setAttributeInternal(LONGDESCRIPTION, value);
    }

    /**Gets the attribute value for the calculated attribute Marketdescription
     */
    public String getMarketdescription() {
        return (String) getAttributeInternal(MARKETDESCRIPTION);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Marketdescription
     */
    public void setMarketdescription(String value) {
        setAttributeInternal(MARKETDESCRIPTION, value);
    }

    /**Gets the attribute value for the calculated attribute Itemtype
     */
    public String getItemtype() {
        return (String) getAttributeInternal(ITEMTYPE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Itemtype
     */
    public void setItemtype(String value) {
        setAttributeInternal(ITEMTYPE, value);
    }

    /**Gets the attribute value for the calculated attribute Primaryuomcode
     */
    public String getPrimaryuomcode() {
        return (String) getAttributeInternal(PRIMARYUOMCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Primaryuomcode
     */
    public void setPrimaryuomcode(String value) {
        setAttributeInternal(PRIMARYUOMCODE, value);
    }

    /**Gets the attribute value for the calculated attribute Productline
     */
    public String getProductline() {
        return (String) getAttributeInternal(PRODUCTLINE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Productline
     */
    public void setProductline(String value) {
        setAttributeInternal(PRODUCTLINE, value);
    }

    /**Gets the attribute value for the calculated attribute Bigclass
     */
    public String getBigclass() {
        return (String) getAttributeInternal(BIGCLASS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Bigclass
     */
    public void setBigclass(String value) {
        setAttributeInternal(BIGCLASS, value);
    }

    /**Gets the attribute value for the calculated attribute Middleclass
     */
    public String getMiddleclass() {
        return (String) getAttributeInternal(MIDDLECLASS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Middleclass
     */
    public void setMiddleclass(String value) {
        setAttributeInternal(MIDDLECLASS, value);
    }

    /**Gets the attribute value for the calculated attribute Bigmiddleclass
     */
    public String getBigmiddleclass() {
        return (String) getAttributeInternal(BIGMIDDLECLASS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Bigmiddleclass
     */
    public void setBigmiddleclass(String value) {
        setAttributeInternal(BIGMIDDLECLASS, value);
    }

    /**Gets the attribute value for the calculated attribute Marketingmodel
     */
    public String getMarketingmodel() {
        return (String) getAttributeInternal(MARKETINGMODEL);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Marketingmodel
     */
    public void setMarketingmodel(String value) {
        setAttributeInternal(MARKETINGMODEL, value);
    }

    /**Gets the attribute value for the calculated attribute Localmodel
     */
    public String getLocalmodel() {
        return (String) getAttributeInternal(LOCALMODEL);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Localmodel
     */
    public void setLocalmodel(String value) {
        setAttributeInternal(LOCALMODEL, value);
    }

    /**Gets the attribute value for the calculated attribute Color
     */
    public String getColor() {
        return (String) getAttributeInternal(COLOR);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Color
     */
    public void setColor(String value) {
        setAttributeInternal(COLOR, value);
    }

    /**Gets the attribute value for the calculated attribute Brandname
     */
    public String getBrandname() {
        return (String) getAttributeInternal(BRANDNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Brandname
     */
    public void setBrandname(String value) {
        setAttributeInternal(BRANDNAME, value);
    }

    /**Gets the attribute value for the calculated attribute Eancode
     */
    public String getEancode() {
        return (String) getAttributeInternal(EANCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Eancode
     */
    public void setEancode(String value) {
        setAttributeInternal(EANCODE, value);
    }

    /**Gets the attribute value for the calculated attribute Regulatoryname
     */
    public String getRegulatoryname() {
        return (String) getAttributeInternal(REGULATORYNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Regulatoryname
     */
    public void setRegulatoryname(String value) {
        setAttributeInternal(REGULATORYNAME, value);
    }

    /**Gets the attribute value for the calculated attribute Upccode
     */
    public String getUpccode() {
        return (String) getAttributeInternal(UPCCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Upccode
     */
    public void setUpccode(String value) {
        setAttributeInternal(UPCCODE, value);
    }

    /**Gets the attribute value for the calculated attribute Productsegment
     */
    public String getProductsegment() {
        return (String) getAttributeInternal(PRODUCTSEGMENT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Productsegment
     */
    public void setProductsegment(String value) {
        setAttributeInternal(PRODUCTSEGMENT, value);
    }

    /**Gets the attribute value for the calculated attribute Fgbigclass
     */
    public String getFgbigclass() {
        return (String) getAttributeInternal(FGBIGCLASS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Fgbigclass
     */
    public void setFgbigclass(String value) {
        setAttributeInternal(FGBIGCLASS, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ITEMNUMBER:
            return getItemnumber();
        case DESCRIPTION:
            return getDescription();
        case LONGDESCRIPTION:
            return getLongdescription();
        case MARKETDESCRIPTION:
            return getMarketdescription();
        case ITEMTYPE:
            return getItemtype();
        case PRIMARYUOMCODE:
            return getPrimaryuomcode();
        case PRODUCTLINE:
            return getProductline();
        case BIGCLASS:
            return getBigclass();
        case MIDDLECLASS:
            return getMiddleclass();
        case BIGMIDDLECLASS:
            return getBigmiddleclass();
        case MARKETINGMODEL:
            return getMarketingmodel();
        case LOCALMODEL:
            return getLocalmodel();
        case COLOR:
            return getColor();
        case BRANDNAME:
            return getBrandname();
        case EANCODE:
            return getEancode();
        case REGULATORYNAME:
            return getRegulatoryname();
        case UPCCODE:
            return getUpccode();
        case PRODUCTSEGMENT:
            return getProductsegment();
        case FGBIGCLASS:
            return getFgbigclass();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ITEMNUMBER:
            setItemnumber((String)value);
            return;
        case DESCRIPTION:
            setDescription((String)value);
            return;
        case LONGDESCRIPTION:
            setLongdescription((String)value);
            return;
        case MARKETDESCRIPTION:
            setMarketdescription((String)value);
            return;
        case ITEMTYPE:
            setItemtype((String)value);
            return;
        case PRIMARYUOMCODE:
            setPrimaryuomcode((String)value);
            return;
        case PRODUCTLINE:
            setProductline((String)value);
            return;
        case BIGCLASS:
            setBigclass((String)value);
            return;
        case MIDDLECLASS:
            setMiddleclass((String)value);
            return;
        case BIGMIDDLECLASS:
            setBigmiddleclass((String)value);
            return;
        case MARKETINGMODEL:
            setMarketingmodel((String)value);
            return;
        case LOCALMODEL:
            setLocalmodel((String)value);
            return;
        case COLOR:
            setColor((String)value);
            return;
        case BRANDNAME:
            setBrandname((String)value);
            return;
        case EANCODE:
            setEancode((String)value);
            return;
        case REGULATORYNAME:
            setRegulatoryname((String)value);
            return;
        case UPCCODE:
            setUpccode((String)value);
            return;
        case PRODUCTSEGMENT:
            setProductsegment((String)value);
            return;
        case FGBIGCLASS:
            setFgbigclass((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
