package Gpcs.oracle.apps.ak.gpcs.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.Row;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OUVORowImpl extends OAViewRowImpl {
    public static final int LEDGERSHORTNAME = 0;
    public static final int ORGCODE = 1;
    public static final int ORGNAME = 2;
    public static final int SELECTFLAG = 3;
    public static final int SOBVO = 4;

    /**This is the default constructor (do not remove)
     */
    public OUVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute LedgerShortName
     */
    public String getLedgerShortName() {
        return (String) getAttributeInternal(LEDGERSHORTNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LedgerShortName
     */
    public void setLedgerShortName(String value) {
        setAttributeInternal(LEDGERSHORTNAME, value);
    }

    /**Gets the attribute value for the calculated attribute OrgCode
     */
    public String getOrgCode() {
        return (String) getAttributeInternal(ORGCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OrgCode
     */
    public void setOrgCode(String value) {
        setAttributeInternal(ORGCODE, value);
    }

    /**Gets the attribute value for the calculated attribute OrgName
     */
    public String getOrgName() {
        return (String) getAttributeInternal(ORGNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OrgName
     */
    public void setOrgName(String value) {
        setAttributeInternal(ORGNAME, value);
    }

    /**Gets the attribute value for the calculated attribute Selectflag
     */
    public String getSelectflag() {
        return (String) getAttributeInternal(SELECTFLAG);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Selectflag
     */
    public void setSelectflag(String value) {
        setAttributeInternal(SELECTFLAG, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case LEDGERSHORTNAME:
            return getLedgerShortName();
        case ORGCODE:
            return getOrgCode();
        case ORGNAME:
            return getOrgName();
        case SELECTFLAG:
            return getSelectflag();
        case SOBVO:
            return getSOBVO();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case LEDGERSHORTNAME:
            setLedgerShortName((String)value);
            return;
        case ORGCODE:
            setOrgCode((String)value);
            return;
        case ORGNAME:
            setOrgName((String)value);
            return;
        case SELECTFLAG:
            setSelectflag((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the associated <code>Row</code> using master-detail link SOBVO
     */
    public Row getSOBVO() {
        return (Row)getAttributeInternal(SOBVO);
    }
}
