package Gpcs.oracle.apps.ak.gpcs.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SOBVORowImpl extends OAViewRowImpl {
    public static final int LEDGERSHORTNAME = 0;
    public static final int ATTRIBUTE2 = 1;
    public static final int SELECTFLAG = 2;
    public static final int OUVO = 3;

    /**This is the default constructor (do not remove)
     */
    public SOBVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute LedgerShortName
     */
    public String getLedgerShortName() {
        return (String) getAttributeInternal(LEDGERSHORTNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LedgerShortName
     */
    public void setLedgerShortName(String value) {
        setAttributeInternal(LEDGERSHORTNAME, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**Gets the attribute value for the calculated attribute Selectflag
     */
    public String getSelectflag() {
        return (String) getAttributeInternal(SELECTFLAG);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Selectflag
     */
    public void setSelectflag(String value) {
        setAttributeInternal(SELECTFLAG, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case LEDGERSHORTNAME:
            return getLedgerShortName();
        case ATTRIBUTE2:
            return getAttribute2();
        case SELECTFLAG:
            return getSelectflag();
        case OUVO:
            return getOUVO();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case LEDGERSHORTNAME:
            setLedgerShortName((String)value);
            return;
        case ATTRIBUTE2:
            setAttribute2((String)value);
            return;
        case SELECTFLAG:
            setSelectflag((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link OUVO
     */
    public RowIterator getOUVO() {
        return (RowIterator)getAttributeInternal(OUVO);
    }
}
