package Gpcs.oracle.apps.ak.gpcs.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TemplateVORowImpl extends OAViewRowImpl {
    public static final int TEMPLATE = 0;
    public static final int ATTRIBUTE1 = 1;

    /**This is the default constructor (do not remove)
     */
    public TemplateVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute Template
     */
    public String getTemplate() {
        return (String) getAttributeInternal(TEMPLATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Template
     */
    public void setTemplate(String value) {
        setAttributeInternal(TEMPLATE, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case TEMPLATE:
            return getTemplate();
        case ATTRIBUTE1:
            return getAttribute1();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case TEMPLATE:
            setTemplate((String)value);
            return;
        case ATTRIBUTE1:
            setAttribute1((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
